### ISSUE TITLE
Preserve subcategory data in menus

### ISSUE THREAD

**Issue by mattdahl** [aspc/mainsite#102]
I.e. All the individual pizza toppings should not be listed as individual items themselves, as if the cafeteria is serving plain pepperoni for lunch. Moreover, some dining halls (the Pomona ones, at least) break down the menu offerings into different section, like "The Grill" or "Vegetarian." We should preserve that data and format our aggregated list of menu items accordingly.

Problem: this is both annoying to parse and hard to model in our ORM.

**Comment by g-rocket** [comment]
Consider fetching the data from [my api](https://github.com/g-rocket/5cMenuFetcher/blob/master/api.md).  It has all of the menu data pre-parsed in a nice easy-to-consume API, and saves both this data and the opening times.
