### ISSUE TITLE
Refactor Course models

### ISSUE THREAD

**Issue by mattdahl** [aspc/mainsite#108]
I drew this up awhile ago, but the basic proposal is to create a model (viz. `GenericSection`) that is a resource that we can reference using our RESTful URL structure. This model would decouple some information that is currently stored in the `Section` model, and thereby allow us to memoize a few data fields that currently have to be recalculated every time a section page is loaded. Right now the existing `Section` model doesn't truly capture the idea of a section page because it is defined as a `<Course, Term>` pair instead of a `<Course, Instructor>` pair. Refactoring this arrangement would provide a (presumably significant) page load speed increase.

![](https://i.imgur.com/PPjklsJ.png)

**Comment by KentShikama** [comment]
@mattdahl What software did you use to draw this UML?

**Comment by mattdahl** [comment]
Honestly I can't remember. I found something online and all I can find saved on my computer is this flat image.

**Comment by KentShikama** [comment]
Can we change the "GenericSection" name to "ReviewAggregator"?

**Comment by mattdahl** [comment]
Yeah, "GenericSection" is a stupid name lol, I just wasn't sure what to call it. "ReviewAggregator" seems weird too though, because it's conceptually more than just that. Maybe "GenericSection" should really be "Section" (i.e. the `<Course, Instructor>` identifier) and the current "Section" should be "SectionInstance" (i.e. the `<Course, Term>` identifier -- a particular instance of a section in a given term)? Feel free to name things how you want, though.

**Comment by KentShikama** [comment]
Yeah "Section" and "SectionInstance" sounds good
