### ISSUE TITLE
The following Facebook pages don't show up on the events page

### ISSUE THREAD

**Issue by KentShikama** [aspc/mainsite#112]
https://www.facebook.com/Pomona-College-Department-of-Psychology-161425830572422/
https://www.facebook.com/Studio-47-146452969759/
http://www.facebook.com/Claremont-French-Club-243965278972416

**Comment by mattdahl** [comment]
I can confirm that some pages (I can't speak about these pages specifically) have consistently resisted our scraping efforts. I never tried to debug it too rigorously, but I think there's something about the format of certain URLs that throws off the way we build Facebook API calls. This is a useful tool... https://developers.facebook.com/tools/explorer

**Comment by KentShikama** [comment]
"I added a bunch of organizations to the ASPC calendar and updated the Google Keep note with more that failed. I noticed a pattern that they were all multi-word names with long strings of numbers after them in the URL's." - Samuel

**Comment by KentShikama** [comment]
I can't think up of an elegant solution right now but if you tweak the URL a bit so that Facebook pages you want to enter are like

https://www.facebook.com/Pomona-College-Department-of-Psychology/161425830572422 (note no trailing slash at the end)

instead of

https://www.facebook.com/Pomona-College-Department-of-Psychology-161425830572422/

the events will be registered
