### ISSUE TITLE
Menu is not working

### ISSUE THREAD

**Issue by patrickshao** [aspc/mainsite#183]
![image](https://cloud.githubusercontent.com/assets/5953037/25776592/de413050-3276-11e7-9beb-5382b0744580.png)

**Comment by mfeng1904** [comment]
The sources that we scrape those 3 menus from are all 404:
http://legacy.cafebonappetit.com/rss/menu/50
https://scrippsdining.sodexomyway.com/Images/WeeklyMenu_tcm1567-149713.htm
http://legacy.cafebonappetit.com/rss/menu/219

**Comment by KentShikama** [comment]
The second link doesn’t seem to be a 404 though?

**Comment by mfeng1904** [comment]
![capture](https://cloud.githubusercontent.com/assets/20055021/25776844/d8410362-327e-11e7-83e2-c512b7b8057f.PNG)

This is what I get when I click the 2nd link. It's supposed to be the menu for this week.
