### ISSUE TITLE
Fix menus

### ISSUE THREAD

**Issue by srichards11** [aspc/mainsite#216]
Web scraping was not working correctly during Spring 2018 (especially for Frary). Look into the root of the problem and find a stable solution.

**Comment by g-rocket** [comment]
One fix is to move to pulling data from [my API](https://github.com/g-rocket/5cMenuFetcher/blob/master/api.md).  I have [another project](https://menu.yancey.io) where I do the scraping myself, and publish a good API from that (which includes stations and hours).  I've been keeping my scrapers up-to-date: the menu formats frequently change and the data itself and its layout is buggy, so the only real solution (I've found) is to manually fix things every once-in-a-while.
