### ISSUE TITLE
Scripps and HMC Dining Services Menus

### ISSUE THREAD

**Issue by acgrobman** [aspc/mainsite#233]
Sodexo recently changed the websites for their dining operations, and the redesign seems to have disabled the functionality for Malott and Hoch.

**Comment by g-rocket** [comment]
You could pull the data from [my API](https://github.com/g-rocket/5cMenuFetcher/blob/master/api.md); I got their menus working.

**Comment by g-rocket** [comment]
Why is this closed?  Mallot and Hoch menus still don't work.
