### ISSUE TITLE
[housing] Image uploads are broken on main

### ISSUE THREAD

**Issue by josePhoenix** [aspc/mainsite#36]
Why? Well, it's not because of a missing jpeg decoder (libjpeg-dev is now installed on Peninsula). It's not because of an old version of django-stdimage or Pillow, both of which have been upgraded. It's not because of request size limits (bumped up to 25 MB for staging and main).

Works on staging.

**Comment by mattdahl** [comment]
For future reference, this error is possibly related?

```
Invalid HTTP_HOST header: '/srv/www/main/run/gunicorn.sock'. The domain name provided is not valid according to RFC 1034/1035.

Request repr():
<WSGIRequest
path:/media/housing/reviews/2014/04/23/IMG_0801.thumbnail.JPG/,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'HTTP_X_FORWARDED_FOR': '134.173.89.73, unix:',
 'PATH_INFO': u'/media/housing/reviews/2014/04/23/IMG_0801.thumbnail.JPG/',
 'QUERY_STRING': '',
 'RAW_URI': '/media/housing/reviews/2014/04/23/IMG_0801.thumbnail.JPG/',
 'REMOTE_ADDR': 'unix',
 'REMOTE_PORT': '',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': '/srv/www/main/run/gunicorn.sock',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gunicorn/18.0',
 'gunicorn.socket': <socket._socketobject object at 0x4603440>,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7ff389e1d270>,
 'wsgi.file_wrapper': <class gunicorn.http.wsgi.FileWrapper at 0x241bd50>,
 'wsgi.input': <gunicorn.http.body.Body object at 0x42ce150>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

See https://github.com/django/django/blob/master/django/http/request.py#L95. `validate_host()` doesn't get called if `settings.DEBUG = True`, which may offer some explanation toward why this works on staging and not main.

Should requests to `/media` like these for housing pictures be served by GUnicorn like this? Perhaps if `nginx` were configured to serve those files - i.e. static image assets - itself, without passing the request onto GUnicorn.

This also may be entirely unrelated; I don't really know what the situation was around the uploads not working in the first place. And this error is not an upload error.
