### ISSUE TITLE
ASPC Course Scheduler "taught by" Name Handling

### ISSUE THREAD

**Issue by patrickshao** [aspc/mainsite#52]
The "taught by" section of the ASPC course scheduler currently handles:
- first name
- last night
- last name, first name

but does not handle:
-  first name last name (which is how the ASPC course review website handles professor names)

This caused me to believe that the professor (Mark Allen) of a 2D design class that I wanted to take was still on sabbatical and hence missed out on registering for the class as by the time I found out that he wasn't gone, the class filled up.

**Comment by mattdahl** [comment]
Damn, sorry about this. I'm surprised no one has complained about this before. See #53.
