### ISSUE TITLE
Course review ratings defaulting to 1 when editing

### ISSUE THREAD

**Issue by frozenpandaman** [aspc/mainsite#86]
After clicking the edit button on a previously-written course review, the stars selector dropdown defaults to 1.

![screen shot 2016-04-15 at 02 45 42](https://cloud.githubusercontent.com/assets/7245874/14548113/495a464a-02b4-11e6-8e83-b5f8987e6d49.png)

![screen shot 2016-04-15 at 02 45 46](https://cloud.githubusercontent.com/assets/7245874/14548115/4af2ef3e-02b4-11e6-894a-748d34c562f4.png)

**Comment by mattdahl** [comment]
indeed, fixed in #85 thanks for the report! @frozenpandaman
