### ISSUE TITLE
Potentially useful code snippets for course reviews

### ISSUE THREAD

**Issue by KentShikama** [aspc/mainsite#94]
Selects all courses and instructors with a rating above 4.8 and that have more than 10 reviews.

```
python manage.py shell_plus
>>> from django.db import connection
>>> cursor = connection.cursor()
>>> cursor.execute("SELECT * FROM courses_course WHERE rating > 4.8 AND (SELECT COUNT(*) FROM courses_coursereview WHERE courses_course.id = courses_coursereview.course_id) > 10")
>>> cursor.fetchall()

>>> cursor.execute("SELECT * FROM courses_instructor WHERE rating > 4.8 AND (SELECT COUNT(*) FROM courses_coursereview WHERE courses_instructor.id = courses_coursereview.instructor_id) > 10")
>>> cursor.fetchall()
```

**Comment by theworldbright** [comment]
A course that requires less than 2 hours per week and is not a PE course

```
>>> cursor.execute("SELECT name FROM courses_course WHERE (SELECT AVG(work_per_week) FROM courses_coursereview WHERE courses_course.id = courses_coursereview.course_id GROUP BY course_id) < 2 AND primary_department_id NOT IN (SELECT id FROM courses_department WHERE code='PE')")
>>> cursor.fetchall()
```

**Comment by theworldbright** [comment]
A course that requires less than 2 hours per week and is not a PE course that will be offered next term

```
>>> cursor.execute("SELECT name FROM courses_course WHERE (SELECT AVG(work_per_week) FROM courses_coursereview WHERE courses_course.id = courses_coursereview.course_id GROUP BY course_id) < 2 AND primary_department_id NOT IN (SELECT id FROM courses_department WHERE code='PE') AND EXISTS (SELECT * FROM courses_section WHERE term_id IN (SELECT id FROM courses_term ORDER BY year DESC, session ASC LIMIT 1) AND courses_course.id = course_id)")
>>> cursor.fetchall()
```

Similarly, courses with rating above 4.5 and more than 10 reviews that will be offered next term.

```
>>> cursor.execute("SELECT * FROM courses_course WHERE rating > 4.8 AND (SELECT COUNT(*) FROM courses_coursereview WHERE courses_course.id = courses_coursereview.course_id) > 10 AND EXISTS (SELECT * FROM courses_section WHERE term_id IN (SELECT id FROM courses_term ORDER BY year DESC, session ASC LIMIT 1) AND courses_course.id = course_id)")
>>> cursor.fetchall()
```

**Comment by ZiqiXiong** [comment]
@KentShikama 
I am thinking about storing each query in a new model object that looks like this:
CourseQuery{
       caption: "I am feeling lazy"
       query: "SELECT name FROM courses_course WHERE (SELECT AVG(work_per_week) FROM courses_coursereview WHERE courses_course.id = courses_coursereview.course_id GROUP BY course_id) < 2 AND primary_department_id NOT IN (SELECT id FROM courses_department WHERE code='PE') AND EXISTS (SELECT * FROM courses_section WHERE term_id IN (SELECT id FROM courses_term ORDER BY year DESC, session ASC LIMIT 1) AND courses_course.id = course_id)"
}
In this way, you can keep adding new creative queries as admin rather than hard-code them every time. 

Now that we can store ratings for sections, can you write SQL queries that find 
* sections with rating above 4.5 and more than 10 reviews that will be offered next term.
*  sections requires less than 2 hours per week and is not a PE course

**Comment by KentShikama** [comment]
@ZiqiXiong 

Section id of courses with rating above 4.5 and more than 10 reviews that will be offered next term.

```
SELECT id FROM courses_section WHERE term_id IN (SELECT id FROM courses_term ORDER BY year DESC, session ASC LIMIT 1) AND courses_section.course_id IN (SELECT id FROM courses_course WHERE rating > 4.5 AND (SELECT COUNT(*) FROM courses_coursereview WHERE courses_course.id = courses_coursereview.course_id) > 10);
```

**Comment by KentShikama** [comment]
The case for "sections requires less than 2 hours per week and is not a PE course" should be a similar conversion
